version: '2'
services:
  nginx:
    build: ./nginx
    restart: always
    # ports: 
    # - 80:8080

  haproxy:
    build: ./haproxy
    restart: always
    links:
      - nginx
    ports: 
    - 81:81
    - 8404:8404